- cinder/volume/drivers/nexenta/nexentaedge/iscsi_ne.py
Placing the _Lx markers back into the code.  No other cleaner solution has has been implemented. 
Partial-Bug: #1384312
Link: https://bugs.launchpad.net/cinder/+bug/1384312
> Implementing the use of _L’x’/i18n markers

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/options.py
NEX-16170 Re-use of iSCSI lun for a new zvol causing errors on linux initiators
Changes:
* Refactored LUN creation: use host group for LUN mappings
* New configuration option: nexenta_host_group_prefix with default value cinder
* Cleanup existing code
> NEX-16170 Re-use of iSCSI lun for a new zvol causing errors on linux initiators

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17099 Cinder volume revert to snapshot: NexentaException: Waited for 120s, but pool pool1 service is still not running
> NEX-17099 Cinder volume revert to snapshot: NexentaException: Waited for 120s, but pool pool1 service is still not running

- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-15960 - Cinder NS 5.x NFS: Refactor mount management on all cinder operations.
NEX-15792 - upgrade 4.x => 5.1.1: cinder driver should support old-style mountpoint.
NEX-17236 - Cinder NS5 NFS: Volume created from snapshot uses wrong provider_location
> Queens/NEX-17236-NEX-15792 NEX-15960

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/utils.py
**Fixed latest Master, use ex2err to convert a Cinder Exception to a NexentaStor error**
*iSCSI*
```
======
Totals
======
Ran: 258 tests in 2566.9528 sec.
- Passed: 249
- Skipped: 9
- Failed: 0
Sum of execute time for each test: 2566.9528 sec.
```
*NFS*
```
======
Totals
======
Ran: 258 tests in 3004.0000 sec.
- Passed: 248
- Skipped: 10
- Failed: 0
Sum of execute time for each test: 2325.3062 sec.
```
> Fixed latest Master, use ex2err to convert a Cinder Exception to a NexentaStor error

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
NEX-17729 Sync NexentaStor5 Cinder driver: Kilo NFS/iSCSI with Master
*Pep8 syntax/lint results*:
```
+ tox -e pep8
pep8 installed: aioeventlet==0.5.1,alembic==0.7.6,amqp==1.4.6,anyjson==0.3.3,appdirs==1.4.0,Babel==1.3,cffi==1.1.2,-e git://git.openstack.org/openstack/cinder.git@15ecdf5814f3b5c2963e46ed9e499608b35e9166#egg=cinder,cliff==1.10.1,cmd2==0.6.8,coverage==3.7.1,cryptography==0.9.1,decorator==3.4.2,discover==0.4.0,docutils==0.12,ecdsa==0.13,enum34==1.0.4,eventlet==0.17.4,extras==0.0.3,fixtures==1.2.0,flake8==2.2.4,functools32==3.2.3.post1,futures==3.0.3,greenlet==0.4.7,hacking==0.10.3,httplib2==0.9.1,idna==2.0,ipaddress==1.0.7,iso8601==0.1.10,Jinja2==2.7.3,jsonpatch==1.11,jsonpointer==1.9,jsonschema==2.5.1,keystonemiddleware==1.5.2,kombu==3 …
```
> NEX-17729 Sync NexentaStor5 Cinder driver: Kilo NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/iscsi.py
*NEX-17918 Coordination backend does not get started in the cinder backup driver*
Remove coordination decorator for Mitaka branch. 
All other coordination changes still exists. We can provide custom patch for Cinder:
https://bugs.launchpad.net/cinder/+bug/1669521
Custom Cinder patch for Mitaka: https://github.com/Nexenta/devstack-ci/blob/master/custom-patches/NEX-17918.diff
Tempest
```
======
Totals
======
Ran: 299 tests in 1927.0000 sec.
- Passed: 293
- Skipped: 6
- Failed: 0
Sum of execute time for each test: 1504.5348 sec.
```
Pep8
```
+ tox -e pep8
pep8 installed: alembic==0.8.4,amqp==1.4.9,anyjson==0.3.3,appdirs==1.4.0,automaton==1.2.0,Babel==2.2.0,bandit==1.0.1,cachetools==1.1.5,certifi==2016.2.28,-e …
```
> NEX-17918 Coordination backend does not get started in the cinder backup driver

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Changes:
* Remove unused modules
* Code cleanup
Pep8:
```
+ tox -e pep8
pep8 installed: alabaster==0.7.11,alembic==1.0.0,amqp==2.3.2,appdirs==1.4.3,asn1crypto==0.24.0,automaton==1.15.0,Babel==2.6.0,bandit==1.5.1,bcrypt==3.1.4,cachetools==2.1.0,castellan==0.20.1,certifi==2018.8.24,cffi==1.11.5,chardet==3.0.4,-e git://git.openstack.org/openstack/cinder.git@677966470df66aa196c9f442036aa42ca2460dad#egg=cinder,cliff==2.13.0,cmd2==0.8.9,contextlib2==0.5.5,coverage==4.5.1,cryptography==2.3.1,cursive==0.2.2,ddt==1.2.0,debtcollector==1.20.0,decorator==4.3.0,defusedxml==0.5.0,deprecation==2.0.6,dnspython==1.15.0,docutils==0.14,dogpile.cache==0.6.7,dulwich==0.19.6,enum34==1.1.6,eventlet==0.24.1,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==2.5.5,fun …
```
> Fixed typos, makes pylint happy

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
More informative exception messages for REST API:
old style:
```
2018-11-11 07:01:53.949 39858 ERROR oslo_service.periodic_task NexentaException: Got bad response from NexentaStor4 Appliance: http://192.168.24.29:8457/rest/nms, status: 503, reason: Service Unavailable, content: XXX
2018-11-11 07:01:53.949 39858 ERROR oslo_service.periodic_task JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
new style:
```
2018-11-11 07:01:53.949 39858 ERROR oslo_service.periodic_task NexentaException: Got bad response from NexentaStor4 Appliance: http://10.3.35.44:8457/rest/nms, data: {"object": "folder", "params": ["pool2", "available|used"], "method": "get_child_props"}, status: 503, reason: Service Unavailable, content: XXX
2018-11-11 07:01:53.949 39858 ERROR oslo_service.periodic_task …
```
> NEX-19177 Openstack volume read only issue - again

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- Added pagination support.
- Added configuration parameters for REST API connect/read
timeouts, connection retries and backoff factor.
- Fixed HA failover.
- Added retries on EBUSY errors.
- Fixed HTTP authentication.
- Disabled non-blocking mandatory locks.
pep8
```
pep8 run-test-pre: PYTHONHASHSEED='1540489231'
pep8 runtests: commands[0] | flake8 .
pep8 runtests: commands[1] | /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 runtests: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/doc/source/ /opt/stack/cinder/releasenotes/notes
```
Tempest iSCSI
```
======
Totals
======
Ran: 273 tests in 4389.0000 sec.
- …
```
> Refactored REST API common code, NFS and iSCSI drivers.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**NEX-19807 Nexenta Cinder driver: support for manage/unmanage volumes**
**Pep8**
```
$ tox -e pep8
pep8 installed: alabaster==0.7.12,alembic==1.0.6,amqp==2.4.0,appdirs==1.4.3,asn1crypto==0.24.0,automaton==1.15.0,Babel==2.6.0,bandit==1.5.1,bcrypt==3.1.6,cachetools==3.0.0,castellan==1.1.0,certifi==2018.11.29,cffi==1.11.5,chardet==3.0.4,-e git://git.openstack.org/openstack/cinder.git@c8976b726a9a19c3860e49ba249738b50e652f14#egg=cinder,cliff==2.14.0,cmd2==0.8.9,contextlib2==0.5.5,coverage==4.5.2,cryptography==2.4.2,cursive==0.2.2,ddt==1.2.0,debtcollector==1.20.0,decorator==4.3.0,defusedxml==0.5.0,dnspython==1.16.0,docutils==0.14,dogpile.cache==0.6.8,dulwich==0.19.10,enum34==1.1.6,eventlet==0.24.1,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8= …
```
> NEX-19807 Nexenta Cinder driver: support for manage/unmanage volumes

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
**NexentaStor5 iSCSI: storage assisted volume migration, retype, volume capabilities**
* NEX-14348 Add migrate volume functionality for 5.x iSCSI
* NEX-18240 Unable to create Cinder volume with user defined properties
* NEX-20168 Workaround for NEX-19823 LUN mapping - inconsistency after renaming a volume
* NEX-14349 Add Retype method to 5.x cinder iSCSI driver
* NEX-18227 Unable to change Cinder volume properties
**Tempest iSCSI**
```
======
Totals
======
Ran: 273 tests in 4119.0000 sec.
- Passed: 269
- Skipped: 4
- Failed: 0
Sum of execute time for each test: 3336.6419 sec.
```
**Unit tests iSCSI**
```
======
Totals
======
Ran: 194 tests in 2.7109 sec.
- Passed: 194
- Skipped: 0
- Failed: 0
Sum of …
```
> NEX-14348 Add retype and migrate volume functionality for NexentaStor5 iSCSI

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**Fixed NFS protocol version for generic volume migration**
**Code style tests**
```
pep8 run-test-pre: PYTHONHASHSEED='837511469'
pep8 start: runtests 
pep8 runtests: commands[0] | flake8 .
pep8 finish: runtests  after 167.44 seconds
pep8 start: run-test-post 
pep8 finish: run-test-post  after 0.00 seconds
___________________________________________________________________ summary ___________________________________________________________________
```
**Unit tests**
```
======
Totals
======
Ran: 196 tests in 4.2176 sec.
- Passed: 196
- Skipped: 0
- Failed: 0
Sum of execute time for each test: 14.4848 sec.
```
**Functional tests** …
> NEX-20320 Cinder NFS generic migration error: mount.nfs: Protocol not supported

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/options.py
**NEX-18892 Sync Cinder driver from Newton to another Openstack branches**
**Code style check**
```
pep8 run-test-pre: PYTHONHASHSEED='2900815627'
[76880] /opt/stack/cinder$ /opt/stack/cinder/.tox/pep8/bin/flake8 .
[77018] /opt/stack/cinder$ /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 run-test: commands[2] | …
```
> NEX-18892 Sync Cinder driver from Newton to another Openstack branches

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**NEX-20387 Our provided openstack driver does not deal gracefully with a slow pool**
```
+        1.4.0 - Refactored NFS driver.
+              - Revert to snapshot support.
+              - Fixed automatic mode for nexenta_rest_protocol.
+              - Added deferred deletion for snapshots.
+              - Added synchronization for NMS REST API calls.
+              - Added configuration parameters for REST API connect/read
+                timeouts, connection retries and backoff factor.
+              - Disabled non-blocking mandatory locks.
+              - Added informative exception messages for REST API.
+              - Improved collection of backend statistics.
```
*Pep8 tests*
```
pep8 run-test: commands[1] | …
```
> NEX-20387 Our provided openstack driver does not deal gracefully with a slow pool

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**Pep8**
```
pep8 run-test-pre: PYTHONHASHSEED='1977895257'
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/doc/source/ /opt/stack/cinder/releasenotes/notes
```
**Unit tests**
```
======
Totals
======
Ran: 196 tests in 2.0000 sec.
- Passed: 196
- Skipped: 0
- Failed: 0
Sum of execute time for each …
```
> Stein: NEX-20387 and NEX-18892 

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**Pep8**
```
pep8 run-test-pre: PYTHONHASHSEED='806523131'
pep8 run-test: commands[0] | python setup.py check --restructuredtext --strict
running check
pep8 run-test: commands[1] | flake8 .
from eventlet.green import socket
```
**Unit tests**
```
======
Ran: 196 tests in 7.0000 sec. …
```
> Rocky: NEX-20387 and NEX-18892

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**Pep8**
```
/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/eventlet/convenience.py:6: DeprecationWarning: EVENTLET_NO_GREENDNS is noop, dnspython is bundled and DNS resolution is always green
from eventlet.green import socket
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/releasenotes/notes
congratulations …
```
> Queens: NEX-20387 and NEX-18892

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**Pep8**
```
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder
```
**Unit tests**
```
======
Totals
======
Ran: 196 tests in 12.0000 sec.
- Passed: 196
- Skipped: 0
- Failed: 0
Sum of execute time for each test: 6.2452 sec.
```
**NexentaStor4 NFS functional tests**
```
====== …
```
> Pike: NEX-20387 and NEX-18892

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
NEX-20582 Volume Attach fails - STMF_ERROR_INVALID_TG
**Pep8**
```
pep8 run-test: commands[0] | flake8 . cinder/common
pep8 run-test: commands[1] | bash -c 'find cinder -type f -regex '"'"'.*\.pot?'"'"' -print0|xargs -0 -n 1 msgfmt --check-format -o /dev/null'
/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
warnings.warn("Do not call this function", DistDeprecationWarning)
pep8 run-test: commands[3] | /opt/stack/cinder/tools/check_exec.py …
```
> Liberty: NEX-20582, NEX-20387 and NEX-18892

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**NEX-20829 Workaround for NEX-18013**
**Pep8**
```
pep8 run-test-pre: PYTHONHASHSEED='2911183928'
[71651] /opt/stack/cinder$ /opt/stack/cinder/.tox/pep8/bin/flake8 .
[71701] /opt/stack/cinder$ /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py …
```
> NEX-20829 Workaround for NEX-18013

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**NEX-21009 Cinder/Manila CI to use python 3.7**
* Improved error messages
* Improved compatibility with initial driver versions
* Added throttle for storage assisted volume migration
**Pep8 syntax check**
```
+ tox -e pep8
...
pep8 run-test-pre: PYTHONHASHSEED='2777420631'
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/doc/source/ /opt/stack/cinder/releasenotes/notes
```
**Python 2.7 unit tests**
```
+ tox -e py27 -- nexenta5
...
======
Totals
======
Ran: 207 tests in 2.0000 sec.
- Passed: …
```
> NEX-21009 Cinder/Manila CI to use python 3.7

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
NEX-20345 Nexenta NFS Cinder driver improperly extends QCOW2 volume size
NEX-21462 Cinder NFS driver must remount volumes created with nbmand enabled
NEX-21461 Cinder NFS driver ignores nexenta_mount_point_base configuration option
NEX-21463 Generic volume migration error: dataset already exists
NEX-21546 Cinder NFS options are available for iSCSI driver and vice versa
NEX-21547 Creating a volume from a snapshot loses the volume type properties
NEX-21555 Update copyrights for Nexenta Cinder drivers
NEX-21593 Workaround for NEX-21577: set refreservation for cloned ZFS volumes
NEX-21594 Workaround for NEX-21586: set correct refreservation thick-provisioned ZFS volumes
NEX-21596 Workaround for NEX-21595: add 'source' to the requested fields
**Fixed flows:**
1. Creating a new volume using the …
> NEX-20345, NEX-21462, NEX-21461, NEX-21463, NEX-21546, NEX-21547, NEX-21555, NEX-21593, NEX-21594 and NEX-21596

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-21629 Implement Image Caching using Cinder's clone_image method**
When Glance cinder store is enabled, the glance image can store locations of cinder volume. When a raw image is cinder volume backed, we can efficiently create a new volume from the image by cloning the backing volume, instead of downloading the image from Glance. We can also make upload-to-image from a volume efficient by creating a cloned volume and add its location to an image.
**pep8**
```
+ tox -e pep8
pep8 run-test-pre: PYTHONHASHSEED='3850372603' …
```
> NEX-21629 Implement Image Caching using Cinder's clone_image method

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/utils.py
```
======
Totals
======
Ran: 263 tests in 3379.1448 sec.
- Passed: 259
- Skipped: 4
- Failed: 0
Sum of execute time for each test: 2595.8630 sec.
```
**NexentaStor5 iSCSI**
```
======
Totals
======
Ran: 263 tests in 3012.0000 sec.
- Passed: 260
- Skipped: 3
- Failed: 0
Sum of execute time for each test: 2282.3874 sec.
```
> NEX-21825 Cinder TypeError: encoding without a string argument

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**NEX-21119 & NEX-22044**
* NEX-22044 Workaround for NEX-22043 NEF RESTful API returns HTTP error 401/Unauthorized on expired license
* NEX-21119 [NexentaBugs #92360] Volume creation fails when one Nexenta server is down
**Changelog**
* Added flag backend_state to report backend status, possible values: **up/down**
Reference: https://specs.openstack.org/openstack/cinder-specs/specs/queens/report-backend-state-in-service-list.html
Status of pool/backend is available for a OpenStack administrator:
```
$ cinder  get-pools --detail
+-----------------------------------+--------------------------------------------------+
| Property                          | Value                                            |
+-----------------------------------+--------------------------------------------------+ …
```
> NEX-21119 & NEX-22044

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**NEX-22103 Unable to create Cinder bootable volumes from large Glance images**
**Tempest NFS**
```
======
Totals
======
Ran: 263 tests in 4362.0000 sec.
- Passed: 259
- Skipped: 4
- Failed: 0
Sum of execute time for each test: 3308.3455 sec.
```
**Tempest iSCSI**
```
======
Totals
======
Ran: 263 tests in 4191.0000 sec.
- Passed: 260
- Skipped: 3
- Failed: 0
Sum of execute time for each test: 3166.7170 sec.
```
**Pep8**
```
pep8 run-test-pre: PYTHONHASHSEED='2023114913'
pep8 run-test: commands[1] | doc8
Scanning...
Validating...
========
Total files scanned = 209
Total files ignored = 463
Total accumulated errors = 0
Detailed error counts:
- CheckCarriageReturn = 0 …
```
> NEX-22103 Unable to create Cinder bootable volumes from large Glance images

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-21119 [NexentaBugs #92360] Volume creation fails when one Nexenta server is down**
**Pep8**
```
+ tox -e pep8
pep8 run-test-pre: PYTHONHASHSEED='2157926149'
pep8 run-test: commands[1] | doc8
Scanning...
Validating...
========
Total files scanned = 209
Total files ignored = 463
Total accumulated errors = 0
Detailed error counts:
- CheckCarriageReturn = 0
- CheckIndentationNoTab = 0
- CheckMaxLineLength = 0
- CheckNewlineEndOfFile = 0
- CheckTrailingWhitespace = 0
- CheckValidity = 0 …
```
> NEX-21119 [NexentaBugs #92360] Volume creation fails when one Nexenta server is down

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22069 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Train**
**Pep8**
```
+ tox -e pep8
...
pep8 run-test-pre: PYTHONHASHSEED='3528551545'
pep8 run-test: commands[1] | doc8
Scanning...
Validating...
========
Total files scanned = 210
Total files ignored = 1829
Total accumulated errors = 0
Detailed error counts:
- CheckCarriageReturn = 0
- CheckIndentationNoTab = 0
- CheckMaxLineLength = 0
- CheckNewlineEndOfFile = 0
- CheckTrailingWhitespace = 0
- CheckValidity = 0 …
```
> NEX-22069 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Train

- cinder/volume/drivers/nexenta/ns5/iscsi.py
**NEX-22450 Failed to get list of manageable volumes: Invalid query parameters (source: rest, name: NefValidateError, code: EBADARG)**
**Tempest**
```
======
Totals
======
Ran: 263 tests in 4177.7876 sec.
- Passed: 260
- Skipped: 3
- Failed: 0
Sum of execute time for each test: 3198.2603 sec.
```
**pep8**
```
+ tox -e pep8
pep8 installed: alembic==1.3.3,amqp==2.5.2,appdirs==1.4.3,attrs==19.3.0,automaton==2.0.0,Babel==2.8.0,bandit==1.6.0,bcrypt==3.1.7,cachetools==4.0.0,castellan==2.0.0,certifi==2019.11.28,cffi==1.14.0,chardet==3.0.4,-e git+https://opendev.org/openstack/cinder.git@a154a1360be62eed0e2bf20937503b55659f4701#egg=cinder,cliff==3.0.0,cmd2==0.8.9,coverage==5.0.3,cryptography==2.8,cursive==0.2.2,ddt …
```
> NEX-22450 Failed to get list of manageable volumes: Invalid query parameters (source: rest, name: NefValidateError, code: EBADARG)

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta_edge.py
- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**Changes:**
* Code style cleanup (Pep8/Python3)
* NEX-22776 Failed to extend non-raw volume: Image …
> NFS driver fixes

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22816 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Icehouce**
**Changes:**
* NEX-22776 …
> NEX-22816 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Icehouce

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22815 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Juno**
**Changes:**
* NEX-22776 Failed …
> NEX-22815 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Juno

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22814 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Kilo**
**Changes:**
* NEX-22776 Failed …
> NEX-22814 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Kilo

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22813 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Liberty**
**Changes:**
* NEX-22776 …
> NEX-22813 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Liberty

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22812 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Mitaka**
**Changes:**
* NEX-22776 …
> NEX-22812 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Mitaka

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22811 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Newton**
**Changes:**
* NEX-22776 …
> NEX-22811 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Newton

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22810 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Ocata**
**Changes:**
* NEX-22776 …
> NEX-22810 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Ocata

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22809 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Pike**
**Changes:**
* NEX-22776 Failed …
> NEX-22809 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Pike

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22808 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Queens**
**Changes:**
* NEX-22776 …
> NEX-22808 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Queens

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22807 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Rocky**
**Changes:**
* NEX-22776 …
> NEX-22807 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Rocky

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22806 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Stein**
**Changes:**
* NEX-22776 …
> NEX-22806 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Stein

- cinder/volume/drivers/nexenta/image.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22805 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Train**
**Changes:**
* NEX-22776 …
> NEX-22805 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Train

- cinder/volume/drivers/nexenta/ns5/nfs.py
Sync with upstream:
```
commit e7b4670516d9db4606efdeae36052c8da6470072
Author: Eric Harney <eharney@redhat.com>
Date:   Mon Jan 18 21:43:32 2021 +0000
Move brick calls from cinder.utils to volume_utils
Move code that calls out to os-brick for connectors,
encryptors, etc., into volume_utils.
This leaves cinder/utils.py more general-purpose
cinder-wide code, which reduces unnecessary binding
between things like "cinder-manage db" and calls
that load much more of cinder's code (and external
libraries like os-brick).
This also means that some drivers only need to
import volume_utils and not cinder.utils.
Partial-Bug: #1912278
Change-Id: Ib2e2960ca354a47d303e0633c7d84e6da4b55b82
```
> NEX-23003 OpenStack Cinder CI failed: AttributeError: module 'cinder.utils' has no attribute 'brick_get_connector_properties'

- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**Description**: Cumulative set of fixes for os-brick NFS connector and Python 3.x
* 147390 After deleting the cinder volume still it shows as mounted on controller
* ES-497 After deleting the cinder volume still it shows as mounted on controller
* NEX-23056 After deleting the cinder volume still it shows as mounted on controller
* NEX-23057 Race condition on mount/unmount Cinder NFS volumes
* NEX-23058 NFS 4.1 mont attempts fails
* NEX-23060 JSON parser error: the JSON object must be str, not 'bytes'
Signed-off-by: Alex Deiter <alex.deiter@gmail.com>
**References**
* Cinder BUG: https://bugs.launchpad.net/cinder/+bug/1559342
* OS-Brick BUG: https://bugs.launchpad.net/os-brick/+bug/1543528
* Python changelog: https://docs.python.org/3/whatsnew/3.6.html#json 
**Pep8 test results**
```
$ …
```
> Cumulative set of fixes for os-brick NFS connector and Python 3.x
