- cinder/volume/drivers/nexenta/__init__.py
- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
New driver v1.2.0 - Added migrate and retype methods
> Added migrate and retype methods

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/options.py
Changes:
* Refactored LUN creation: use host group for LUN mappings
* New configuration option: nexenta_host_group_prefix with default value cinder
* Cleanup existing code
> NEX-16170 Re-use of iSCSI lun for a new zvol causing errors on linux initiators

- cinder/volume/drivers/nexenta/ns5/iscsi.py
> NEX-16962 QA CI: tempest test_volume_revert_to_snapshot failed

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
NEX-17014 ERROR oslo_service.periodic_task TypeError: format requires a mapping
```
======
Totals
======
Ran: 288 tests in 1476.0000 sec.
- Passed: 285
- Skipped: 3
- Failed: 0
Sum of execute time for each test: 723.2487 sec.
```
> NEX-17014 ERROR oslo_service.periodic_task TypeError: format requires a mapping

- cinder/volume/drivers/nexenta/ns5/iscsi.py
**NEX-17103 Cinder volume attach error for active-active HA environment: VolumeDeviceNotFound: Volume device not found at .**
Changes:
* Fixed active-active HA env
* Fixed terminate connection in case of force detach
* Fixed debug code
> NEX-17103 Cinder volume attach error for active-active HA environment: VolumeDeviceNotFound: Volume device not found at .

- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-15960 - Cinder NS 5.x NFS: Refactor mount management on all cinder operations.
NEX-15792 - upgrade 4.x => 5.1.1: cinder driver should support old-style mountpoint.
NEX-17236 - Cinder NS5 NFS: Volume created from snapshot uses wrong provider_location
> Pike/NEX-17236-NEX-15792 NEX-15960

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
NEX-17316 Cinder iSCSI driver makes unavailable Active-Active NS HA cluster
> NEX-17316 Cinder iSCSI driver makes unavailable Active-Active NS HA cluster

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17014 QA CI: ERROR oslo_service.periodic_task TypeError: format requires a mapping
Changes:
* Backported code from Newton
> NEX-17014 QA CI: ERROR oslo_service.periodic_task TypeError: format requires a mapping

- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17345 QA CI: NFS driver error: Stale file handle
> NEX-17345 QA CI: NFS driver error: Stale file handle

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
> Nex 17345 mitaka postfix

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
Sync Master branch for NexentaStor5 iSCSI
> Sync Master branch for NexentaStor5 iSCSI

- cinder/volume/drivers/nexenta/ns5/nfs.py
> Fix a typo/mis-merge

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
> Sync Master NexentaStor5/NFS

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
> Fixed latest Master

- cinder/volume/drivers/nexenta/ns5/nfs.py
Fixed NFS mount options for volume migration/retype
> Fixed NFS mount options for volume migration/retype

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
> Fixed mount/unmunt volume operations

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Added driver_ssl_cert_verify for HA failover, fixed volume unmount operation
> Added driver_ssl_cert_verify for HA failover, fixed volume unmount operation

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/utils.py
*Juno from master*
```
======
Totals
======
Ran: 314 tests in 1009.0000 sec.
- Passed: 303
- Skipped: 11
- Failed: 0
Sum of execute time for each test: 659.7400 sec.
```
> Juno from master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/utils.py
Fixed typos, makes pep8 happy.
> Fixed typos, makes pep8 happy.

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17603 Failed to migrate volume: Dependent datasets must be destroyed first
> NEX-17603 Failed to migrate volume: Dependent datasets must be destroyed first

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
Merge latest fixes from Master
> Merge latest fixes from Master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-16478 Ericsson's Cinder drivers for Mirantis Pike**
Merge latest changes from Master
> NEX-16478 Ericsson's Cinder drivers for Mirantis Pike

- cinder/volume/drivers/nexenta/ns5/iscsi.py
> Merge Pike changes

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
NEX-17656 Sync Queens NFS/iSCSI with Master
> NEX-17656 Sync Queens NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17688 Cinder Volume removed in Cinder, but still exist on NexentaStor5
> NEX-17688 Cinder Volume removed in Cinder, but still exist on NexentaStor5

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
NEX-17694 Sync NexentaStor5 Cinder driver: Newton NFS/iSCSI with Master
> NEX-17694 Sync NexentaStor5 Cinder driver: Newton NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17703 Sync NexentaStor5 Cinder driver: Queens NFS/iSCSI with Master
> NEX-17703 Sync NexentaStor5 Cinder driver: Queens NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17704 Sync NexentaStor5 Cinder driver: Pike NFS/iSCSI with Master
> NEX-17704 Sync NexentaStor5 Cinder driver: Pike NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17705 Sync NexentaStor5 Cinder driver: Mitaka NFS/iSCSI with Master
> NEX-17705 Sync NexentaStor5 Cinder driver: Mitaka NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-17706 Sync NexentaStor5 Cinder driver: Juno NFS/iSCSI with Master
> NEX-17706 Sync NexentaStor5 Cinder driver: Juno NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-17763 Sync NexentaStor5 Cinder driver: Icehouse NFS/iSCSI with Master**
**Pep8 stuyle/lint results**
```
pep8 installdeps: -r/opt/stack/cinder/requirements.txt, -r/opt/stack/cinder/test-requirements.txt
pep8 runtests: PYTHONHASHSEED='0'
pep8 runtests: commands[0] | flake8 . cinder/common
pep8 runtests: commands[1] | flake8 --filename=cinder* bin
```
**Tempest results for iSCSI**
```
======
Totals
======
Ran: 314 tests in 0.0000 sec.
- Passed: 302
- Skipped: 12
- Failed: 0
Sum of execute time for each test: 580.1331 sec.
```
**Tempest results for NFS**
```
======
Totals
======
Ran: …
```
> NEX-17763 Sync NexentaStor5 Cinder driver: Icehouse NFS/iSCSI with Master

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
NEX-17963 Improve Cinder Logging
NEX-17967 Auto switching to HTTPS connection is broken
> NEX-17967 and NEX-17963

- cinder/volume/drivers/nexenta/iscsi.py
NEX-18033 Unable to create view - STMF_ERROR_INVALID_TG
> NEX-18033 Unable to create view - STMF_ERROR_INVALID_TG

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-18399 Consistency groups for Nexenta Cinder driver
> NEX-18399 Consistency groups for Nexenta Cinder driver

- cinder/volume/drivers/nexenta/ns5/iscsi.py
*NEX-16474 Implement multi-attach for Queens and later releases*
Changes:
* Added volume multi-attach logic for terminate volume connection:
```
Sep 24 22:34:40 openstack-queens-ns5-iscsi cinder-volume[7077]: 
DEBUG cinder.volume.drivers.nexenta.ns5.iscsi 
[req-70eeb286-69d3-4d8d-8b55-89fbb4984a76 
req-844461db-3c70-4fab-8881-bd6adb9f1271 
tempest-AttachVolumeMultiAttachTest-365607399 None]
Detected multiple connections on host openstack-queens-ns5-iscsi [10.3.196.21] 
for volume volume-6c7f6337-de8c-4390-a5ad-d6e27f5dc309, 
skip terminate volume connection 
{{terminate_connection /opt/stack/cinder/cinder/volume/drivers/nexenta/ns5/iscsi.py:366}}
``` 
* Enabled multi-attach feature for iSCSI backend
* Fixed debug messages
Tempest results:
```
ci runtests: commands[3] | ostestr …
```
> NEX-16474 Implement multiattach for Queens and later releases

- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-19305 Redundant hpr/activate call in initialize_connection
> NEX-19305 Redundant hpr/activate call in initialize_connection

- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge upstream change: https://github.com/openstack/cinder/commit/923fc520744271f0431f8e39797b081263ed4f13
> NEX-19525 NfsException: Unexpected error while running umount command

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-19801 Cinder NFS driver: support for NexentaStor5 tenants
> NEX-19801 Cinder NFS driver: support for NexentaStor5 tenants

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
> NEX-19995 Unit tests for Nexenta Cinder driver

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
back porting changes from Master
> NEX-20047 CLONE NEX-19524 Improperly url-encoded filesystem names in ns5/nfs.py

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
> Sync with upstream

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-20135 Nexenta Cinder driver workaround for NEX-19094
> NEX-20135 Nexenta Cinder driver workaround for NEX-19094

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NexentaStor5 NFS: storage assisted volume migration, retype, volume capabilities
* NEX-18240 Unable to create Cinder volume with user defined properties
* NEX-18227 Unable to change Cinder volume properties
**Unut tests**
```
======
Totals
======
Ran: 196 tests in 3.6809 sec.
- Passed: 196
- Skipped: 0
- Failed: 0
Sum of execute time for each test: 13.4699 sec.
```
**Pep8 tests**
```
pep8 run-test-pre: PYTHONHASHSEED='1102650391'
pep8 runtests: commands[0] | flake8 .
pep8 runtests: commands[1] | /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 runtests: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/doc/source/ /opt/stack/cinde
r/releasenotes/notes
___________________________________ summary …
```
> NEX-17420 QA CI: NFS driver volume migration OSError: [Errno 2] No such file or directory

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
> NEX-20323 NexentaStor5 iSCSI backend error: TRIM ioctl failed: Operation not supported

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
**NEX-20519 NFS Cinder volume must be activated before initialize connection**
**Style tests**
```
```
**Unit tests**
```
======
Totals
======
Ran: 196 tests in 4.4979 sec.
- Passed: 196
- Skipped: 0
- Failed: 0
Sum of execute time for each test: 16.1958 sec.
```
**Functional tests**
```
======
Totals
======
Ran: 273 tests in 4822.0000 sec.
- Passed: 267
- Skipped: 6
- Failed: 0
Sum of execute time for each test: 3824.3165 sec.
```
> NEX-20519 NFS Cinder volume must be activated before initialize connection

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Backward compatibility for older Python/Requests and unit tests.
> Backward compatibility for older Python/Requests and unit tests.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Backward compatibility for older Python/Requests and unit tests.
>  Backward compatibility for older Python/Requests and unit tests.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Master.
> Merge latest changes from Mitaka into Master.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Stein.
> Merge latest changes from Mitaka into Stein.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Rocky.
> Merge latest changes from Mitaka into Rocky.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Queens.
> Merge latest changes from Mitaka into Queens.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Pike.
> Merge latest changes from Mitaka into Pike.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Ocata.
> Merge latest changes from Mitaka into Ocata.

- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_iscsi.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_jsonrpc.py
- cinder/tests/unit/volume/drivers/nexenta/test_nexenta5_nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Merge latest changes from Mitaka into Newton.
> Merge latest changes from Mitaka into Newton.

- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
Be compatible with Python 2 and 3
> Be compatible with Python 2 and 3

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
NEX-20582 Volume Attach fails - STMF_ERROR_INVALID_TG
**Functional tests**
```
======
Totals
======
Ran: 299 tests in 2458.0000 sec.
- Passed: 293
- Skipped: 6
- Failed: 0
Sum of execute time for each test: 1807.8511 sec.
```
> Mitaka: NEX-20582, NEX-20387 and NEX-18892

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**Pep8**
```
pep8 finish: run-test  after 43.63 seconds
pep8 start: run-test-post 
pep8 finish: run-test-post  after 0.00 seconds
_______________________________________________________________________________________ summary _______________________________________________________________________________________
```
**Unit tests**
```
======
Totals
======
Ran: 192 tests in 18.0000 sec.
- Passed: 192
- Skipped: 0
- Failed: 0
Sum of execute time for each test: 8.0369 sec.
```
**NexentaStor4 iSCSI functional tests**
```
======
Totals
======
Ran: 336 tests …
```
> Newton: NEX-20387 and NEX-18892

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**Unit tests**
```
Totals
======
Ran: 192 tests in 14.0000 sec.
- Passed: 192
- Skipped: 0
- Failed: 0
Sum of execute time for each test: 5.4670 sec.
```
**NexentaStor4 iSCSI functional tests**
```
======
Totals
======
Ran: 241 tests in 2772.0000 sec.
- Passed: 232
- Skipped: 9
- Failed: 0
Sum of execute time for each test: 2230.7177 sec.
```
**NexentaStor4 NFS functional tests**
```
======
Totals
======
Ran: 241 tests in 3038.0000 sec.
- Passed: 231
- Skipped: 10
- Failed: 0
Sum of execute time for each test: …
```
> Ocata: NEX-20387 and NEX-18892

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
**NEX-20720 Cinder driver ConnectionError: ('Connection aborted.', BadStatusLine("''",))**
**Pep8**
```
pep8 run-test-pre: PYTHONHASHSEED='2960282168'
[63250] /opt/stack/cinder$ /opt/stack/cinder/.tox/pep8/bin/flake8 .
[63302] /opt/stack/cinder$ /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 run-test: commands[2] …
```
> NEX-20720 Cinder driver ConnectionError: ('Connection aborted.', BadStatusLine("''",))

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Stein: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Rocky: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Queens: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Pike: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Ocata: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Newton: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
> Mitaka: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/options.py
> Liberty: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/options.py
> Kilo: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/options.py
> Juno: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/options.py
> Icehouse: NEX-20720 and NEX-20773

- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
NEX-21717 Volume service failed to start: ImportError: cannot import name utils
> NEX-21717 Volume service failed to start: ImportError: cannot import name utils

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22175 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Icehouse**
**Pep8**
```
+ tox -e pep8
pep8 installdeps: -r/opt/stack/cinder/requirements.txt, -r/opt/stack/cinder/test-requirements.txt, -c/opt/stack/cinder/../requirements/upper-constraints.txt
pep8 runtests: PYTHONHASHSEED='0'
pep8 runtests: commands[0] | flake8 . cinder/common
pep8 runtests: commands[1] | flake8 --filename=cinder* bin
```
```
======
Totals
======
Ran: 314 tests in 833.0000 sec.
- Passed: 303
- Skipped: 11
- Failed: 0
Sum of execute time for each test: 541.8412 sec.
```
**NexentaStor5 …
> NEX-22175 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Icehouse

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22174 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Juno**
**Pep8**
```
+ tox -e pep8
pep8 installdeps: -r/opt/stack/cinder/requirements.txt, -r/opt/stack/cinder/test-requirements.txt
pep8 runtests: PYTHONHASHSEED='0'
pep8 runtests: commands[0] | flake8 . cinder/common
pep8 runtests: commands[1] | flake8 --filename=cinder* bin
pep8 runtests: commands[2] | bash -c find cinder -type f -regex '.*\.pot?' -print0|xargs -0 -n 1 msgfmt --check-format -o /dev/null
```
```
======
Totals
======
Ran: 314 tests in 1046.0000 sec.
- Passed: 303
- Skipped: 11
- Failed: 0 …
```
> NEX-22174 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Juno

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22173 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Kilo**
**Pep8**
```
+ tox -e pep8
pep8 installdeps: -r/opt/stack/cinder/requirements.txt, -r/opt/stack/cinder/test-requirements.txt, -c/opt/stack/cinder/../requirements/upper-constraints.txt
pep8 run-test: commands[0] | flake8 . cinder/common
```
```
======
Totals
======
Ran: 314 tests in 1255.0000 sec.
- Passed: 304
- Skipped: 10
- Failed: 0
Sum of execute time for each test: 775.4857 sec.
```
```
====== …
```
> NEX-22173 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Kilo

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22172 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Liberty**
**Pep8**
```+ tox -e pep8
pep8 installdeps: -r/opt/stack/cinder/requirements.txt, -r/opt/stack/cinder/test-requirements.txt
pep8 run-test: commands[0] | flake8 . cinder/common
pep8 run-test: commands[3] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder
```
```
======
Totals
======
Ran: 294 tests in 1395.0000 sec.
- Passed: 289
- Skipped: 5
- …
```
> NEX-22172 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Liberty

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22171 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Mitaka**
**Pep8**
```
+ tox -e pep8
pep8 run-test: commands[2] | /opt/stack/cinder/tools/config/check_uptodate.sh --checkopts
pep8 run-test: commands[3] | /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 run-test: commands[4] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder
```
```
======
Totals
======
Ran: 299 tests in 1634.0000 sec.
- Passed: 293
- Skipped: 6
- Failed: 0
Sum of execute time for each …
```
> NEX-22171 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Mitaka

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22170 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Newton**
**Pep8**
```
+ tox -e pep8
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder
```
```
======
Totals
======
Ran: 336 tests in 3187.0000 sec.
- Passed: 328
- Skipped: 8
- Failed: 0
Sum of execute time for each test: 2341.8649 sec.
```
```
======
Totals
======
Ran: 336 tests in 2864.0000 sec.
- Passed: 328
- Skipped: 8
- …
```
> NEX-22170 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Newton

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22169 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Ocata**
**Pep8**
```
+ tox -e pep8
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder
```
```
======
Totals
======
Ran: 241 tests in 0.0000 sec.
- Passed: 231
- Skipped: 10
- Failed: 0
Sum of execute time for each test: 1911.0656 sec.
```
```
======
Totals
======
Ran: 244 tests in 3844.0000 sec.
- Passed: 236
- Skipped: 8
- …
```
> NEX-22169 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Ocata

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22168 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Pike**
**Pep8**
```
+ tox -e pep8
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder
```
```
======
Totals
======
Ran: 250 tests in 0.0000 sec.
- Passed: 241
- Skipped: 9
- Failed: 0
Sum of execute time for each test: 2288.0107 sec.
```
```
======
Totals
======
Ran: 253 tests in 0.0000 sec.
- Passed: 247
- Skipped: 6
- …
```
> NEX-22168 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Pike

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22167 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Queens**
**Pep8**
```
+ tox -e pep8
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/releasenotes/notes
```
```
======
Totals
======
Ran: 271 tests in 2788.0000 sec.
- Passed: 262
- Skipped: 9
- Failed: 0
Sum of execute time for each test: 2086.8189 sec.
```
```
======
Totals
======
Ran: 274 tests in …
```
> NEX-22167 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Queens

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22166 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Rocky**
**Pep8**
```
+ tox -e pep8
...
pep8 run-test-pre: PYTHONHASHSEED='2907371980'
pep8 run-test: commands[0] | python setup.py check --restructuredtext --strict
running check
```
```
======
Totals
======
Ran: 271 tests in 0.0000 sec.
- Passed: 262
- Skipped: 9
- Failed: 0
Sum of execute time for each …
```
> NEX-22166 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Rocky

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/iscsi.py
- cinder/volume/drivers/nexenta/nexentaedge/jsonrpc.py
- cinder/volume/drivers/nexenta/nexentaedge/nbd.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22137 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Stein**
**Pep8**
```
pep8 run-test-pre: PYTHONHASHSEED='2926328281'
[116624] /opt/stack/cinder$ /opt/stack/cinder/tools/config/check_uptodate.sh
pep8 run-test: commands[2] | /opt/stack/cinder/tools/check_exec.py /opt/stack/cinder/cinder /opt/stack/cinder/doc/source/ /opt/stack/cinder/releasenotes/notes
setting PATH=/opt/stack/cinder/.tox/pep8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/ …
```
> NEX-22137 Sync NexentaStor Cinder NFS/iSCSI drivers: Master => Stein

- cinder/volume/drivers/nexenta/iscsi.py
- cinder/volume/drivers/nexenta/jsonrpc.py
- cinder/volume/drivers/nexenta/nfs.py
- cinder/volume/drivers/nexenta/ns5/iscsi.py
- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
- cinder/volume/drivers/nexenta/utils.py
**NEX-22307 Name from location header as a result for POST API Calls**
**Pep8**
```
+ tox -e pep8
pep8 run-test-pre: PYTHONHASHSEED='3966749366'
pep8 run-test: commands[1] | doc8
Scanning...
Validating...
========
Total files scanned = 204
Total files ignored = 435
Total accumulated errors = 0
Detailed error counts:
- CheckCarriageReturn = 0
- CheckIndentationNoTab = 0
- CheckMaxLineLength = 0
- CheckNewlineEndOfFile = 0
- CheckTrailingWhitespace = 0
- CheckValidity = 0 …
```
> NEX-22307 Name from location header as a result for POST API Calls

- cinder/volume/drivers/nexenta/ns5/jsonrpc.py
- cinder/volume/drivers/nexenta/ns5/nfs.py
- cinder/volume/drivers/nexenta/options.py
**NEX-22721 Add support NexentaStor5 vSolution API**
**Tempest for disabled vSolution**
```
======
Totals
======
Ran: 268 tests in 4815.5120 sec.
- Passed: 264
- Skipped: 4
- Failed: 0
Sum of execute time for each test: 3580.7254 sec.
```
**Tempest for enabled vSolution**
```
======
Totals
======
Ran: 268 tests in 4817.0176 sec.
- Passed: 264
- Skipped: 4
- Failed: 0
Sum of execute time for each test: 3618.5699 sec.
```
> NEX-22721 Add support NexentaStor5 vSolution API

- cinder/volume/drivers/nexenta/ns5/nfs.py
**NEX-22722 NFS Security Enhancements: allows secure NFS environment setup**
**NEX-22724 Cinder backup unexpected error: permission denied for cinder NFS backend**
**Tempest**
```
======
Totals
======
Ran: 268 tests in 4742.9263 sec.
- Passed: 264
- Skipped: 4
- Failed: 0
Sum of execute time for each test: 3514.8749 sec.
```
> NEX-22722 and NEX-22724 
